"""empty message

Revision ID: 0416faf3387b
Revises: ae1625870114
Create Date: 2024-01-11 04:24:21.035516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0416faf3387b'
down_revision: Union[str, None] = 'ae1625870114'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'author',
               existing_type=sa.VARCHAR(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'author',
               existing_type=sa.String(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
