"""empty message

Revision ID: 6fe654b2863b
Revises: 0416faf3387b
Create Date: 2024-01-11 09:43:00.139702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fe654b2863b'
down_revision: Union[str, None] = '0416faf3387b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('country', sa.String(), nullable=True))
    op.alter_column('books', 'author',
               existing_type=sa.VARCHAR(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'author',
               existing_type=sa.String(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('authors', 'country')
    # ### end Alembic commands ###
